Improve labels id converter.
Was failing for high label values due to:
new_unique_ids = numpy.arange(0, max_label_id + 1, dtype='uint64')
ValueError: Maximum allowed size exceeded